# Generated by Django 4.0.6 on 2022-07-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(default='', max_length=200)),
                ('departure_city', models.CharField(default='', max_length=200)),
                ('departure_time', models.CharField(default='', max_length=200)),
                ('arrival_city', models.CharField(default='', max_length=200)),
                ('arrival_time', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
