# Generated by Django 4.0.6 on 2022-07-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='arrival_city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='arrival_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='departure_city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='departure_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='flightdetails',
            name='flight_number',
            field=models.CharField(max_length=200),
        ),
    ]
